name: aoba
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  get_it: ^7.2.0
  veee: ^0.9.3
  worker_manager: ^4.3.3
  # Network
  graphql: ^5.1.1
  flutter_web_auth: ^0.4.1
  # Data & storage
  flutter_secure_storage: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Widgets & UI
  auto_route: ^4.2.1
  sliver_tools: ^0.2.6
  scroll_builder: ^0.0.1
  # Util
  stringr: ^1.0.0
  date_time_format: ^2.0.1
  json_annotation: ^4.6.0
  collection: ^1.16.0
  flextensions: ^0.1.0
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_lints: ^2.0.0
  # Test
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # Generators
  build_runner: ^2.1.11
  json_serializable: ^6.3.0
  auto_route_generator: ^4.0.0
  hive_generator: ^1.1.3
  graphql_codegen: ^0.9.0

flutter:
  uses-material-design: true
