name: aoba
description: A modest client app for anilist.co

publish_to: 'none'

version: 0.0.1+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  get_it: ^7.6.4
  veee: ^0.10.0
  # Network
  graphql: ^5.1.3
  # Data & storage
  isar: 3.0.5
  isar_flutter_libs: 3.0.5
  # Widgets & UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.5
  auto_route: ^7.8.4
  sliver_tools: ^0.2.12
  scroll_builder: ^1.1.0
  timer_builder: ^2.0.0
  flutter_html: ^3.0.0-alpha.6
  shimmer: ^3.0.0
  intl: ^0.18.1
  # OS / Platform
  path_provider: ^2.1.1
  # Util
  vector_math: ^2.1.4
  material_color_utilities: ^0.8.0
  stringr: ^1.0.0
  date_time_format: ^2.0.1
  duration: ^3.0.13
  json_annotation: ^4.8.1
  collection: ^1.18.0
  flextensions: ^0.2.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.3
  # Test
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.1
  # Generators
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  isar_generator: 3.0.5
  graphql_codegen: ^0.13.7
  code_builder: ^4.7.0
  # Packaging
  msix: ^3.16.4

dependency_overrides:
  material_color_utilities: ^0.8.0
  intl: ^0.18.1

flutter:
  uses-material-design: true

  assets:
      - assets/images/

flutter_gen:
  output: lib/data/assets/
  integrations:
    flutter_svg: true
