name: aoba
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  get_it: ^7.2.0
  veee: ^0.10.0
  worker_manager: ^4.4.0
  # Network
  graphql: ^5.1.1
  flutter_web_auth: ^0.5.0
  # Data & storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Widgets & UI
  auto_route: ^5.0.2
  sliver_tools: ^0.2.8
  scroll_builder: ^0.0.1
  flutter_html: ^3.0.0-alpha.6
  shimmer: ^2.0.0
  # Util
  stringr: ^1.0.0
  date_time_format: ^2.0.1
  duration: ^3.0.12
  json_annotation: ^4.7.0
  collection: ^1.16.0
  flextensions: ^0.1.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  # Test
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # Generators
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.2
  hive_generator: ^1.1.3
  graphql_codegen: ^0.11.2
  code_builder: ^4.3.0

dependency_overrides:

flutter:
  uses-material-design: true
