name: aoba
description: A modest client app for anilist.co

publish_to: 'none'

version: 0.0.1+4

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  get_it: ^7.2.0
  veee: ^0.10.0
  worker_manager: ^4.4.0
  # Network
  graphql: ^5.1.1
  flutter_web_auth: ^0.5.0
  # Data & storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  # Widgets & UI
  flutter_svg: ^1.1.6
  auto_route: ^5.0.2
  sliver_tools: ^0.2.8
  scroll_builder: ^0.0.1
  timer_builder: ^2.0.0
  flutter_html: ^3.0.0-alpha.6
  shimmer: ^2.0.0
  # Util
  vector_math: ^2.1.4
  material_color_utilities: ^0.2.0
  stringr: ^1.0.0
  date_time_format: ^2.0.1
  duration: ^3.0.12
  json_annotation: ^4.7.0
  collection: ^1.16.0
  flextensions: ^0.1.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  # Test
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # Generators
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.2
  hive_generator: ^1.1.3
  isar_generator: ^3.0.5
  graphql_codegen: ^0.11.2
  code_builder: ^4.3.0
  # Packaging
  msix: ^3.7.0

dependency_overrides:
  material_color_utilities: ^0.2.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/
