name: Test & Deploy

on:
  push:
    branches: dev

jobs:
  job:
    name: Test & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Get dependencies
        run: flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build

      - name: Get the number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Run tests
        run: flutter test -j ${{ steps.cpu-cores.outputs.count }}

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: Prepare Google Play credentials for Fastlane
        run: echo -n "${{ secrets.GOOGLE_PLAY_JSON_KEY }}" | base64 --decode > ./android/fastlane/key.json

      - name: Prepare key.properties
        run: echo -n "${{ secrets.KEY_PROPERTIES }}" | base64 --decode > ./android/key.properties

      - name: Prepare upload.keystore
        run: echo -n "${{ secrets.UPLOAD_KEYSTORE }}" | base64 --decode > ./android/upload.keystore

      - name: Build AAB & Deploy
        run: cd android && bundle install && bundle exec fastlane internal build_number:$GITHUB_RUN_NUMBER && cd ..

      - name: Build APK
        run: flutter build apk --release --build-number $GITHUB_RUN_NUMBER

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
