name: Deploy

on:
  push:
    branches: dev

jobs:
  job:
    name: Test & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Get dependencies
        run: flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build

      - name: Get the number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Run tests
        run: flutter test -j ${{ steps.cpu-cores.outputs.count }}

      - name: Build
        run: flutter build apk --release --build-number $GITHUB_RUN_NUMBER

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_DISTRIBUTION_CREDENTIALS }}
          groups: internal
          file: /home/runner/work/aoba/aoba/build/app/outputs/flutter-apk/app-release.apk
          debug: true
